import test from 'node:test';import assert from 'node:assert/strict';import {evaluate,fingerprint} from './creative-qa.js';
const keys=['advantage_plus_creative','image_auto_crop','image_uncrop','image_enhancement','image_animation','image_background_gen','text_generation','text_optimizations','music_generation'];
function fixture(){return {adset:{targeting:{publisher_platforms:['facebook','instagram'],facebook_positions:['feed'],instagram_positions:['stream','story']}},creative:{contextual_multi_ads:{enroll_status:'OPT_OUT'},degrees_of_freedom_spec:{creative_features_spec:Object.fromEntries(keys.map(k=>[k,{enroll_status:'OPT_OUT'}]))},asset_feed_spec:{optimization_type:'PLACEMENT',images:[{hash:'feed',adlabels:[{name:'feed'}]},{hash:'story',adlabels:[{name:'story'}]}],asset_customization_rules:[{priority:1,image_label:{name:'story'},customization_spec:{publisher_platforms:['instagram'],instagram_positions:['story']}},{priority:2,image_label:{name:'feed'},customization_spec:{publisher_platforms:['facebook','instagram'],facebook_positions:['feed'],instagram_positions:['stream']}}]}}};}
const images={feed:{hash:'feed',width:1080,height:1350},story:{hash:'story',width:1080,height:1920}};
test('checks all four enabled device/placement previews',()=>{const r=evaluate(fixture(),images);assert.deepEqual(r.issues,[]);assert.ok(r.required.includes('DESKTOP_FEED_STANDARD'));assert.ok(r.required.includes('INSTAGRAM_STORY'))});
test('fails closed for enabled or missing enhancements',()=>{const a=fixture();a.creative.degrees_of_freedom_spec.creative_features_spec.audio={enroll_status:'OPT_IN'};assert.match(evaluate(a,images).issues.join(),/audio/);delete a.creative.degrees_of_freedom_spec.creative_features_spec.image_auto_crop;assert.match(evaluate(a,images).issues.join(),/image_auto_crop/)});
test('wrong story asset dimensions block readiness',()=>{assert.match(evaluate(fixture(),{...images,story:{...images.story,height:1350}}).issues.join(),/1080 × 1920/)});
test('new unsupported placements block readiness',()=>{const a=fixture();a.adset.targeting.instagram_positions.push('unknown_future_placement');assert.match(evaluate(a,images).issues.join(),/Unreviewed placement/)});
test('fingerprint ignores object key order but invalidates changed configuration',async()=>{assert.equal(await fingerprint({b:2,a:1}),await fingerprint({a:1,b:2}));assert.notEqual(await fingerprint({creative:'a'}),await fingerprint({creative:'b'}))});

test('video mapping preserves multiword platform and position names',()=>{const a=fixture();a.adset.targeting={publisher_platforms:['facebook','audience_network'],device_platforms:['mobile'],facebook_positions:['facebook_reels'],audience_network_positions:['rewarded_video']};const spec=a.creative.asset_feed_spec;spec.images=[];spec.videos=[{video_id:'vertical',adlabels:[{name:'story'}]},{video_id:'feed',adlabels:[{name:'feed'}]}];spec.asset_customization_rules=[{priority:1,video_label:{name:'story'},customization_spec:{publisher_platforms:['facebook'],facebook_positions:['facebook_reels']}},{priority:2,video_label:{name:'feed'},customization_spec:{publisher_platforms:['audience_network'],audience_network_positions:['rewarded_video']}}];const videos={vertical:{video_id:'vertical',width:1080,height:1920,status:'ready'},feed:{video_id:'feed',width:1080,height:1350,status:'ready'}};const result=evaluate(a,{},videos);assert.deepEqual(result.issues,[]);assert.equal(result.assets.audience_network_rewarded_video.video_id,'feed');assert.equal(result.formatPlacements.FACEBOOK_REELS_MOBILE,'facebook_facebook_reels');videos.vertical.height=1350;assert.match(evaluate(a,{},videos).issues.join(),/1080 × 1920/);});

 test('compact placements require their square asset, not the feed crop',()=>{const a=fixture();a.adset.targeting={publisher_platforms:['facebook'],facebook_positions:['marketplace','right_hand_column']};a.creative.asset_feed_spec.images=[{hash:'compact',adlabels:[{name:'compact'}]}];a.creative.asset_feed_spec.asset_customization_rules=[{priority:1,image_label:{name:'compact'},customization_spec:{publisher_platforms:['facebook'],facebook_positions:['marketplace','right_hand_column']}}];assert.deepEqual(evaluate(a,{compact:{hash:'compact',width:1080,height:1080}}).issues,[]);assert.match(evaluate(a,{compact:{hash:'compact',width:1080,height:1350}}).issues.join(),/1080 × 1080/);});

test('Instagram search uses a portrait asset while retaining visual review requirements',()=>{const a=fixture();a.adset.targeting={publisher_platforms:['instagram'],instagram_positions:['ig_search']};a.creative.asset_feed_spec.asset_customization_rules=[{priority:1,image_label:{name:'feed'},customization_spec:{publisher_platforms:['instagram'],instagram_positions:['ig_search']}}];const r=evaluate(a,images);assert.deepEqual(r.issues,[]);assert.ok(r.required.includes('INSTAGRAM_SEARCH_GRID'));assert.ok(r.required.includes('INSTAGRAM_SEARCH_CHAIN'));assert.match(evaluate(a,{...images,feed:{width:1080,height:1080}}).issues.join(),/1080 × 1350/);});


test('Facebook search requires both live API search previews and its square asset',()=>{
 const a=fixture();a.adset.targeting={publisher_platforms:['facebook'],facebook_positions:['search']};
 a.creative.asset_feed_spec.images=[{hash:'compact',adlabels:[{name:'compact'}]}];
 a.creative.asset_feed_spec.asset_customization_rules=[{priority:1,image_label:{name:'compact'},customization_spec:{publisher_platforms:['facebook'],facebook_positions:['search']}}];
 const r=evaluate(a,{compact:{hash:'compact',width:1080,height:1080}});
 assert.deepEqual(r.issues,[]);
 assert.deepEqual(r.required,['SEARCH_SERP_ADS_MOBILE','MARKETPLACE_SEARCH_ADS_MOBILE']);
 assert.equal(r.formatPlacements.SEARCH_SERP_ADS_MOBILE,'facebook_search');
 assert.equal(r.formatPlacements.MARKETPLACE_SEARCH_ADS_MOBILE,'facebook_search');
 assert.match(evaluate(a,{compact:{width:1080,height:1350}}).issues.join(),/1080 × 1080/);
});
