import test from 'node:test';import assert from 'node:assert/strict';import {evaluate,fingerprint} from './creative-qa.js';
const keys=['advantage_plus_creative','image_auto_crop','image_uncrop','image_enhancement','image_animation','image_background_gen','text_generation','text_optimizations','music_generation'];
function fixture(){return {adset:{targeting:{publisher_platforms:['facebook','instagram'],facebook_positions:['feed'],instagram_positions:['stream','story']}},creative:{contextual_multi_ads:{enroll_status:'OPT_OUT'},degrees_of_freedom_spec:{creative_features_spec:Object.fromEntries(keys.map(k=>[k,{enroll_status:'OPT_OUT'}]))},asset_feed_spec:{optimization_type:'PLACEMENT',images:[{hash:'feed',adlabels:[{name:'feed'}]},{hash:'story',adlabels:[{name:'story'}]}],asset_customization_rules:[{priority:1,image_label:{name:'story'},customization_spec:{publisher_platforms:['instagram'],instagram_positions:['story']}},{priority:2,image_label:{name:'feed'},customization_spec:{publisher_platforms:['facebook','instagram'],facebook_positions:['feed'],instagram_positions:['stream']}}]}}};}
const images={feed:{hash:'feed',width:1080,height:1350},story:{hash:'story',width:1080,height:1920}};
test('checks all four enabled device/placement previews',()=>{const r=evaluate(fixture(),images);assert.deepEqual(r.issues,[]);assert.equal(r.required.length,4)});
test('fails closed for enabled or missing enhancements',()=>{const a=fixture();a.creative.degrees_of_freedom_spec.creative_features_spec.audio={enroll_status:'OPT_IN'};assert.match(evaluate(a,images).issues.join(),/audio/);delete a.creative.degrees_of_freedom_spec.creative_features_spec.image_auto_crop;assert.match(evaluate(a,images).issues.join(),/image_auto_crop/)});
test('wrong story asset dimensions block readiness',()=>{assert.match(evaluate(fixture(),{...images,story:{...images.story,height:1350}}).issues.join(),/1080 × 1920/)});
test('new unsupported placements block readiness',()=>{const a=fixture();a.adset.targeting.instagram_positions.push('reels');assert.match(evaluate(a,images).issues.join(),/Unreviewed placement/)});
test('fingerprint ignores object key order but invalidates changed configuration',async()=>{assert.equal(await fingerprint({b:2,a:1}),await fingerprint({a:1,b:2}));assert.notEqual(await fingerprint({creative:'a'}),await fingerprint({creative:'b'}))});
